import { Injectable } from '@nestjs/common';
import * as PDFDocument from 'pdfkit';

interface TakeoffSummaryData {
  project: { name: string; address?: string; city?: string; state?: string };
  company: { name: string; phone?: string; address?: string };
  categories: { name: string; code: string; count: number; totalQuantity: number; unit: string }[];
  totalItems: number;
  generatedAt: string;
}

interface EstimateSummaryData {
  project: { name: string; address?: string; city?: string; state?: string };
  company: { name: string; phone?: string; address?: string };
  estimate: {
    name: string; version: number; status: string;
    subtotal: number; markupPercent: number; markupAmount: number;
    taxPercent: number; taxAmount: number; totalAmount: number;
  };
  lines: { description: string; quantity: number; unit: string; materialCost: number; laborCost: number; totalCost: number }[];
  generatedAt: string;
}

interface ProposalData extends EstimateSummaryData {
  validUntil?: string;
  notes?: string;
}

@Injectable()
export class PdfGeneratorService {

  async generateTakeoffSummary(data: TakeoffSummaryData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text(data.company.name, { align: 'center' });
      if (data.company.address) doc.fontSize(9).font('Helvetica').text(data.company.address, { align: 'center' });
      if (data.company.phone) doc.fontSize(9).text(data.company.phone, { align: 'center' });
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(562, doc.y).stroke('#2563EB');
      doc.moveDown(0.5);

      // Title
      doc.fontSize(16).font('Helvetica-Bold').text('Takeoff Summary Report', { align: 'center' });
      doc.moveDown(0.5);

      // Project Info
      doc.fontSize(10).font('Helvetica-Bold').text('Project: ', { continued: true });
      doc.font('Helvetica').text(data.project.name);
      if (data.project.address) {
        doc.font('Helvetica-Bold').text('Address: ', { continued: true });
        doc.font('Helvetica').text(
          [data.project.address, data.project.city, data.project.state].filter(Boolean).join(', ')
        );
      }
      doc.font('Helvetica-Bold').text('Date: ', { continued: true });
      doc.font('Helvetica').text(data.generatedAt);
      doc.font('Helvetica-Bold').text('Total Items: ', { continued: true });
      doc.font('Helvetica').text(String(data.totalItems));
      doc.moveDown();

      // Table Header
      const tableTop = doc.y;
      const colX = [50, 200, 340, 420, 500];
      doc.rect(50, tableTop, 512, 20).fill('#2563EB');
      doc.fillColor('#FFFFFF').fontSize(9).font('Helvetica-Bold');
      doc.text('Category', colX[0] + 5, tableTop + 5, { width: 145 });
      doc.text('Code', colX[1] + 5, tableTop + 5, { width: 135 });
      doc.text('Count', colX[2] + 5, tableTop + 5, { width: 75, align: 'right' });
      doc.text('Quantity', colX[3] + 5, tableTop + 5, { width: 75, align: 'right' });
      doc.text('Unit', colX[4] + 5, tableTop + 5, { width: 55, align: 'right' });

      // Table Rows
      let rowY = tableTop + 22;
      doc.fillColor('#000000').font('Helvetica').fontSize(9);
      data.categories.forEach((cat, idx) => {
        if (rowY > 700) {
          doc.addPage();
          rowY = 50;
        }
        if (idx % 2 === 0) doc.rect(50, rowY - 2, 512, 18).fill('#F3F4F6');
        doc.fillColor('#000000');
        doc.text(cat.name, colX[0] + 5, rowY, { width: 145 });
        doc.text(cat.code, colX[1] + 5, rowY, { width: 135 });
        doc.text(String(cat.count), colX[2] + 5, rowY, { width: 75, align: 'right' });
        doc.text(cat.totalQuantity.toFixed(1), colX[3] + 5, rowY, { width: 75, align: 'right' });
        doc.text(cat.unit, colX[4] + 5, rowY, { width: 55, align: 'right' });
        rowY += 18;
      });

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).fillColor('#9CA3AF').text(
        `Generated by FinishVision on ${data.generatedAt}`,
        50, 740, { align: 'center', width: 512 }
      );

      doc.end();
    });
  }

  async generateEstimateSummary(data: EstimateSummaryData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text(data.company.name, { align: 'center' });
      if (data.company.address) doc.fontSize(9).font('Helvetica').text(data.company.address, { align: 'center' });
      if (data.company.phone) doc.fontSize(9).text(data.company.phone, { align: 'center' });
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(562, doc.y).stroke('#2563EB');
      doc.moveDown(0.5);

      // Title
      doc.fontSize(16).font('Helvetica-Bold').text('Estimate Summary', { align: 'center' });
      doc.moveDown(0.5);

      // Project & Estimate Info
      doc.fontSize(10).font('Helvetica-Bold').text('Project: ', { continued: true });
      doc.font('Helvetica').text(data.project.name);
      doc.font('Helvetica-Bold').text('Estimate: ', { continued: true });
      doc.font('Helvetica').text(`${data.estimate.name} (v${data.estimate.version})`);
      doc.font('Helvetica-Bold').text('Status: ', { continued: true });
      doc.font('Helvetica').text(data.estimate.status);
      doc.font('Helvetica-Bold').text('Date: ', { continued: true });
      doc.font('Helvetica').text(data.generatedAt);
      doc.moveDown();

      // Line Items Table
      const tableTop = doc.y;
      const colX = [50, 230, 290, 340, 410, 480];
      doc.rect(50, tableTop, 512, 20).fill('#2563EB');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');
      doc.text('Description', colX[0] + 5, tableTop + 5, { width: 175 });
      doc.text('Qty', colX[1] + 5, tableTop + 5, { width: 55, align: 'right' });
      doc.text('Unit', colX[2] + 5, tableTop + 5, { width: 45, align: 'right' });
      doc.text('Material', colX[3] + 5, tableTop + 5, { width: 65, align: 'right' });
      doc.text('Labor', colX[4] + 5, tableTop + 5, { width: 65, align: 'right' });
      doc.text('Total', colX[5] + 5, tableTop + 5, { width: 75, align: 'right' });

      let rowY = tableTop + 22;
      doc.fillColor('#000000').font('Helvetica').fontSize(8);
      data.lines.forEach((line, idx) => {
        if (rowY > 680) {
          doc.addPage();
          rowY = 50;
        }
        if (idx % 2 === 0) doc.rect(50, rowY - 2, 512, 18).fill('#F3F4F6');
        doc.fillColor('#000000');
        doc.text(line.description, colX[0] + 5, rowY, { width: 175 });
        doc.text(line.quantity.toLocaleString(), colX[1] + 5, rowY, { width: 55, align: 'right' });
        doc.text(line.unit, colX[2] + 5, rowY, { width: 45, align: 'right' });
        doc.text(`$${line.materialCost.toFixed(2)}`, colX[3] + 5, rowY, { width: 65, align: 'right' });
        doc.text(`$${line.laborCost.toFixed(2)}`, colX[4] + 5, rowY, { width: 65, align: 'right' });
        doc.text(`$${line.totalCost.toFixed(2)}`, colX[5] + 5, rowY, { width: 75, align: 'right' });
        rowY += 18;
      });

      // Totals
      rowY += 10;
      doc.moveTo(380, rowY).lineTo(562, rowY).stroke('#D1D5DB');
      rowY += 8;
      const fmt = (n: number) => `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
      doc.fontSize(9).font('Helvetica');
      doc.text('Subtotal:', 380, rowY, { width: 100, align: 'right' });
      doc.text(fmt(data.estimate.subtotal), 485, rowY, { width: 75, align: 'right' });
      rowY += 16;
      doc.text(`Markup (${data.estimate.markupPercent}%):`, 380, rowY, { width: 100, align: 'right' });
      doc.text(fmt(data.estimate.markupAmount), 485, rowY, { width: 75, align: 'right' });
      rowY += 16;
      doc.text(`Tax (${data.estimate.taxPercent}%):`, 380, rowY, { width: 100, align: 'right' });
      doc.text(fmt(data.estimate.taxAmount), 485, rowY, { width: 75, align: 'right' });
      rowY += 4;
      doc.moveTo(380, rowY + 12).lineTo(562, rowY + 12).stroke('#2563EB');
      rowY += 20;
      doc.fontSize(12).font('Helvetica-Bold');
      doc.text('TOTAL:', 380, rowY, { width: 100, align: 'right' });
      doc.fillColor('#2563EB').text(fmt(data.estimate.totalAmount), 485, rowY, { width: 75, align: 'right' });

      // Footer
      doc.fontSize(8).fillColor('#9CA3AF').text(
        `Generated by FinishVision on ${data.generatedAt}`,
        50, 740, { align: 'center', width: 512 }
      );

      doc.end();
    });
  }

  async generateProposal(data: ProposalData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Company Header
      doc.fontSize(22).font('Helvetica-Bold').fillColor('#1E40AF').text(data.company.name, { align: 'center' });
      if (data.company.address) doc.fontSize(9).font('Helvetica').fillColor('#6B7280').text(data.company.address, { align: 'center' });
      if (data.company.phone) doc.fontSize(9).text(data.company.phone, { align: 'center' });
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(562, doc.y).lineWidth(2).stroke('#2563EB');
      doc.moveDown(0.8);

      // Proposal Title
      doc.fontSize(18).font('Helvetica-Bold').fillColor('#111827').text('PROPOSAL', { align: 'center' });
      doc.moveDown(0.8);

      // Project Info Box
      const boxY = doc.y;
      doc.rect(50, boxY, 512, 70).fill('#F0F4FF');
      doc.fillColor('#111827').fontSize(10).font('Helvetica-Bold');
      doc.text('Project:', 65, boxY + 10, { continued: true });
      doc.font('Helvetica').text(`  ${data.project.name}`);
      if (data.project.address) {
        doc.font('Helvetica-Bold').text('Location:', 65, boxY + 28, { continued: true });
        doc.font('Helvetica').text(`  ${[data.project.address, data.project.city, data.project.state].filter(Boolean).join(', ')}`);
      }
      doc.font('Helvetica-Bold').text('Date:', 65, boxY + 46, { continued: true });
      doc.font('Helvetica').text(`  ${data.generatedAt}`);
      if (data.validUntil) {
        doc.font('Helvetica-Bold').text('Valid Until:', 350, boxY + 46, { continued: true });
        doc.font('Helvetica').text(`  ${data.validUntil}`);
      }
      doc.y = boxY + 80;
      doc.moveDown(0.5);

      // Scope of Work
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#1E40AF').text('Scope of Work');
      doc.moveDown(0.3);

      // Line Items
      const tableTop = doc.y;
      const colX = [50, 310, 390, 480];
      doc.rect(50, tableTop, 512, 22).fill('#1E40AF');
      doc.fillColor('#FFFFFF').fontSize(9).font('Helvetica-Bold');
      doc.text('Description', colX[0] + 8, tableTop + 6, { width: 255 });
      doc.text('Qty / Unit', colX[1] + 5, tableTop + 6, { width: 75, align: 'right' });
      doc.text('Unit Price', colX[2] + 5, tableTop + 6, { width: 85, align: 'right' });
      doc.text('Amount', colX[3] + 5, tableTop + 6, { width: 75, align: 'right' });

      let rowY = tableTop + 24;
      doc.fillColor('#000000').font('Helvetica').fontSize(9);
      data.lines.forEach((line, idx) => {
        if (rowY > 650) {
          doc.addPage();
          rowY = 50;
        }
        if (idx % 2 === 0) doc.rect(50, rowY - 2, 512, 20).fill('#F9FAFB');
        doc.fillColor('#374151');
        doc.text(line.description, colX[0] + 8, rowY + 1, { width: 255 });
        doc.text(`${line.quantity} ${line.unit}`, colX[1] + 5, rowY + 1, { width: 75, align: 'right' });
        const unitPrice = line.quantity > 0 ? line.totalCost / line.quantity : 0;
        doc.text(`$${unitPrice.toFixed(2)}`, colX[2] + 5, rowY + 1, { width: 85, align: 'right' });
        doc.text(`$${line.totalCost.toFixed(2)}`, colX[3] + 5, rowY + 1, { width: 75, align: 'right' });
        rowY += 20;
      });

      // Totals Box
      rowY += 15;
      const fmt = (n: number) => `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
      doc.rect(350, rowY, 212, 90).fill('#F0F4FF');
      doc.fillColor('#374151').fontSize(9).font('Helvetica');
      doc.text('Subtotal:', 360, rowY + 8, { width: 110, align: 'right' });
      doc.text(fmt(data.estimate.subtotal), 475, rowY + 8, { width: 80, align: 'right' });
      doc.text(`Markup (${data.estimate.markupPercent}%):`, 360, rowY + 24, { width: 110, align: 'right' });
      doc.text(fmt(data.estimate.markupAmount), 475, rowY + 24, { width: 80, align: 'right' });
      doc.text(`Tax (${data.estimate.taxPercent}%):`, 360, rowY + 40, { width: 110, align: 'right' });
      doc.text(fmt(data.estimate.taxAmount), 475, rowY + 40, { width: 80, align: 'right' });
      doc.moveTo(360, rowY + 58).lineTo(555, rowY + 58).stroke('#2563EB');
      doc.fontSize(13).font('Helvetica-Bold').fillColor('#1E40AF');
      doc.text('TOTAL:', 360, rowY + 65, { width: 110, align: 'right' });
      doc.text(fmt(data.estimate.totalAmount), 475, rowY + 65, { width: 80, align: 'right' });

      // Notes
      if (data.notes) {
        doc.y = rowY + 105;
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#374151').text('Notes:');
        doc.fontSize(9).font('Helvetica').text(data.notes);
      }

      // Signature Lines
      const sigY = 680;
      doc.moveTo(50, sigY).lineTo(250, sigY).stroke('#D1D5DB');
      doc.moveTo(312, sigY).lineTo(562, sigY).stroke('#D1D5DB');
      doc.fontSize(9).fillColor('#6B7280').font('Helvetica');
      doc.text('Contractor Signature / Date', 50, sigY + 5, { width: 200, align: 'center' });
      doc.text('Client Signature / Date', 312, sigY + 5, { width: 250, align: 'center' });

      // Footer
      doc.fontSize(8).fillColor('#9CA3AF').text(
        `Generated by FinishVision | ${data.company.name}`,
        50, 750, { align: 'center', width: 512 }
      );

      doc.end();
    });
  }

  async generateCsv(headers: string[], rows: string[][]): Promise<Buffer> {
    const escape = (val: string) => {
      if (val.includes(',') || val.includes('"') || val.includes('\n')) {
        return `"${val.replace(/"/g, '""')}"`;
      }
      return val;
    };
    const lines = [
      headers.map(escape).join(','),
      ...rows.map(row => row.map(escape).join(',')),
    ];
    return Buffer.from(lines.join('\n'), 'utf-8');
  }
}
